- name: Add keys
  apt_key:
    url: "{{ item.url }}"
    id: "{{ item.id }}"
  loop:
    - url: https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
      id: FAB46452
    - url: https://www.mongodb.org/static/pgp/server-3.4.asc
      id: A15703C6
    - url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      id: "68576280"

- name: Add repositories
  apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    update_cache: false
  loop:
    - filename: bigbluebutton
      repo: deb https://ubuntu.bigbluebutton.org/bionic-230 bigbluebutton-bionic main
    - filename: mongodb-org-4.2
      repo: deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse
    - filename: nodesource
      repo: deb https://deb.nodesource.com/node_12.x bionic main

- name: Configure PPA repositories
  apt_repository:
    repo: "{{ item }}"
    update_cache: false
  loop:
    - ppa:bigbluebutton/support
    - ppa:libreoffice/ppa
    - ppa:rmescandon/yq
    - ppa:certbot/certbot

# Do it once instead of redoing it every repo is added.
- name: Make cache
  apt:
    update_cache: true
